Fix deprecated error
This commit fixes the following error:
```
ErrorException: E_DEPRECATED: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in /www/data/Physik.FSPHYS/php_include/de/uni_muenster/fsphys/Util.php:81
```